bot:
  cat-bot:
    username: 'infcatbot'
    api:
      random-cat-gif: 'https://cataas.com/cat/gif'
      random-cat: 'https://cataas.com/cat'
      max-file-size: '1' #MB
    command:
      random-cat-photo:
        command: 'photo'
        description: 'Send random photo with cat'
      random-cat-gif:
        command: 'gif'
        description: 'Send random gif with cat'